### ISSUE TITLE
Infinite gold

### ISSUE THREAD

**Issue by chrisinajar** [AngelArenaAllstars/aaa#9]
It is important to the mode that players have infinite gold capacity.

AAR appears to implement it by polling users gold (or perhaps hooking on gold gain events) and storing off / replacing gold above / below a certain line. Looking at other mods, it's possible that the cap on gold simply doesn't exist anymore and we may not need to do this at all. For example, AABS displays gold well into the 6 digits.

Figure it out, post results.

**Comment by Zarnotox** [comment]
It seems like Angel Arena Black star made their own gold.lua and used their functions to override the api from dota2. (gold.lua) 

I also looked at Angel Arena Reborn because their gold is limited to 80000 but they are doing a lot of weird stuff. Every time it checks if you have more than 80000 gold it also checks if you are meepo and need to change your boots while fixing some doom. (addon_game_mode.lua 1522-1562)

(renamed files to *.txt so I could upload them)

[addon_game_mode.txt](https://github.com/AngelArenaAllstars/aaa/files/694944/addon_game_mode.txt)

[gold.txt](https://github.com/AngelArenaAllstars/aaa/files/694947/gold.txt)

**Comment by chrisinajar** [comment]
It's likely we'll need to implement basically exactly this. Great findings!
Post if you find any other solutions.

**Comment by chrisinajar** [comment]
The basic system is now in, from here it's optimizations and refinements.
